services:
  postgres:
    image: postgres:15-alpine
    container_name: nadoumishop-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: nadoumishop-redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  maildev:
    image: maildev/maildev
    container_name: nadoumishop-maildev
    restart: always
    ports:
      - "1081:1080"
      - "1026:1025"

volumes:
  postgres_data:
  redis_data:
